on:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v9
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: 1,
              owner: 'andershol',
              repo: 'notification-test',
              body: 'Comment from action' })
